### ISSUE TITLE
Replace 'contexts' with 'scopes'

### ISSUE THREAD

**Issue by ManasiGandhi** [OpenLiberty/guide-cdi-intro#100]
Replaced 'contexts' with 'scopes' in line 56.

I'm working on an article on CDI's and using this resource as a reference. Just noticed that the term 'contexts' and would like to suggest that 'scopes' might be a more appropriate term here. Please advise.

**Comment by evelinec** [comment]
Thank you for raising the issue. See response in the PR. Thanks.

**Comment by evelinec** [comment]
The issue had been handled. Thank you.
