### ISSUE TITLE
Hotspot issue

### ISSUE THREAD

**Issue by Omegashin** [OpenLiberty/guide-cdi-intro#112]
Here's a screenshot:
<img width="612" alt="Screen Shot 2019-09-11 at 2 09 57 PM" src="https://user-images.githubusercontent.com/17682945/64723121-dfba6700-d49d-11e9-8b2a-6c35b9dd3800.png">

**Comment by DannyS03** [comment]
- Seems like the hotspot was implemented like this intentionally since a new file does not need to be created, and the guide creator is just referencing it for the user.

**Comment by yeekangc** [comment]
What is the exact issue, @Omegashin?

Do you mean the block for SystemEndpointTest.java looks different?
