### ISSUE TITLE
Guide doesn't seem to make a good case for using RequestScope

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/guide-cdi-intro#114]
Similar to #82, I can't see any reason why any of the `@RequestScoped` classes couldn't be `@ApplicationScoped` instead as none of them appear to hold any state.

In general, having stateless classes is good, but if they are stateless, they should be `@ApplicationScoped`.

Note: I had someone in a workshop question why the resource class was RequestScoped.

**Comment by yeekangc** [comment]
Good point.  Either they should be `@ApplicationScoped` or show a better/stronger case for `@RequestScoped`.
