### ISSUE TITLE
Thread safety & lack of injection in InventoryManager

### ISSUE THREAD

**Issue by ldelaigue** [OpenLiberty/guide-cdi-intro#66]
It seems that method get() in the InventoryManager is not Thread-safe since it uses a shared SystemClient object.
Also, SystemClient should probably be injected also (with a Request scope, but I wonder how that could be done in a class with Application scope). The tutorial would benefit from that since it would emphasize the benefits of DI

**Comment by yeekangc** [comment]
Thank you, @ldelaigue.  We might have missed to deliver some fixes to the code here.  Looking into it.

**Comment by evelinec** [comment]
- testing the other guides that uses MP rest client with the thread safe configs

**Comment by proubatsis** [comment]
Can you confirm whether or not this issue has been fixed please @ldelaigue ? If it has, please close the issue.
