### ISSUE TITLE
javax.ws.rs-api version conflicts

### ISSUE THREAD

**Issue by jefrajames** [OpenLiberty/guide-cdi-intro#68]
While reworking the example, I've tried to use the connectTimeout and readTimeout methods on ClientBuilder. These methods have been introduced with JAX-RS 2.1. Curiously, they are not accessible from my IDE (Eclipse) which just sees the JAX-RS 2.0 version.
It seems there is conflict on javax.ws-rs-api versions in the pom.xml :
- cxf-rt-rs-client:3.1.11 depends on javax.ws.rs-api:2.0.1
- jaxrs-2.1:18.0.0.3 depends on javax.ws.rs-api:2.1 but is omitted for conflict with 2.0.1
As a workaround, I've excluded javax.ws.rs-api dependency from cxf-rt-rs-client in the pom.xml and everything works fine.

**Comment by jefrajames** [comment]
There is the same issue with other tutorials: rest, consuming rest etc ...

**Comment by yeekangc** [comment]
Thank you, @jefrajames.  We are looking into this and will address ASAP.

**Comment by gkwan-ibm** [comment]
@jefrajames , you may update cxf-rt-rs-client and cxf-rt-rs-extension-providers to use 3.2.6 in the pom.xml. 

The pom.xml files will be updated by the pull request #74.
