### ISSUE TITLE
General User Feedback and Minor Multipane Issues

### ISSUE THREAD

**Issue by Rachelwrq** [OpenLiberty/guide-cdi-intro#70]
#### Introduction
- [x] Add scopes after manage to make sure the introduction is consistent to the first paragraph in `What you'll learn` section

#### What you'll learn
- [x] Change the flow of the first paragraph

#### Handling dependencies in the application
- [x] Minor grammar issues

### Multipane Issue
- [x] The hotspot for `testSuite()` method is yet to be created, as well as for `@Test` annotation
- [x] For highlighting, exclude annotations when discussing the method to avoid distractions. 
- [x] Change instructions in Action Arrow. For example: Change `Inventory Manager class file` to `InventoryManager class`

**Comment by justineechen** [comment]
### Checklist for multipane conversion
**Through the browser:**
- [ ] Read over guide and run through all commands (copy and paste using browser etc..)
- [ ] Test the actual application (use it, hit endpoints, etc.)
- [ ] No files in the middle panel (guide section)
- [ ] Appropriate files are being displayed on the right hand side at the right time
- [ ] Any mention of code in the right panel should be hot spotted
- [ ] Make sure hotspots actually point to the correct lines
- [ ] Any actions to the code (Create, replace) should be put in an arrow (code_command)
- [ ] All code commands are highlighting the right code
- [ ] Any actions to look at the code should be a hotspot
- [ ] Guide attribution is present

**In the README.adoc:**
- [ ] Tags in the front matter are correct
     - [ ] If `:page-guide-category: none` remove `:page-essential:` and `:page-essential-order:`

**In other files:**
- [ ] Failsafe plugin and Surefire plugin updates if applicable
- [ ] Parent POM update
     - [ ] start directory
     - [ ] finish directory
- [ ] Files are formatted correctly
- [ ] .travis.yaml file is updated accordingly

**Comment by justineechen** [comment]
- [ ] Two files in one subsection issue is prominent in this guide in Managing scopes and contexts

**Comment by justineechen** [comment]
<img width="872" alt="screen shot 2018-12-12 at 3 36 32 pm" src="https://user-images.githubusercontent.com/18709242/49897388-015dc380-fe24-11e8-8e9b-49162e640711.png">

There may be an issue where we cannot gray out this output unless we hard code the commands above it.

**Comment by andrewdes** [comment]
# General

```              
<execution>
    <id>start-server</id>
    <phase>pre-integration-test</phase>
    <goals>
        <goal>start-server</goal>
     </goals>
</execution>
```

- [ ] Can be removed from the `pom.xml` files

# Handling dependencies in the application

- [ ] Throughout the guide I see `application-scoped`, is the `-` necessary? While looking online I see `application scoped`. Perhaps we should look into this.

# Testing the inventory application 

- [ ] InventoryEndpointTest should be in backticks in the code command

**Comment by justineechen** [comment]
This guide has successfully been converted to multipane and has no blockers.
