### ISSUE TITLE
Multipane Issues

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/guide-cdi-intro#77]
**Injecting a dependency**
- [ ] Should `InventoryManager` bean and `InventoryResource` class be hotspotted?
- [x] I think `SystemClient` should be displayed in the right pane when it is being talked about in the final paragraph of this section

**Testing the inventory application**
- [x] "This client must also be registered with a JSON-P provider (`JsrJsonpProvider`) to process JSON resources." -> `JsrJsonpProvider` should hotspot to the line where the client is registered with a JSON-P provider
- [x] "See the following descriptions of the test cases:" -> The test cases following this line should be put in a bulleted list. It looks awkward starting sentences with hotspotted method names
- [x] "Finally, a `system` test class in the.." -> This should be hotspotted and display the test class in the right pane

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/guide-cdi-intro/commit/a9206dd30620ba14baa724361000cf92273f0ced

**Comment by andrewdes** [comment]
"Finally, you have a client component SystemClient that can be found in `src/main/java/io/openliberty/guides/inventory/client`." -> "Finally, you have a client component SystemClient that can be found in **the** `src/main/java/io/openliberty/guides/inventory/client` **directory**."

**Building and running the application**
- [ ] "This goal starts an Open Liberty server instance. Your Maven `pom.xml` is already configured to start the application in this server instance." -> should `pom.xml` be hotspotted and displayed in the right pane?

**Testing the application**
- [ ] "Finally, a `system` test class in the `src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java` file is included for you to test the basic functionality of the system service." -> `system` hotspot is wrong **and** `SystemEndpointTest.java` file displays copyright comment in the right pane
- [ ] "To see whether the tests detect a failure, change the endpoint for the inventory service in the `src/main/java/io/openliberty/guides/inventory/InventoryResource.java` file to something else, then run the Maven build again. You see a test failure occur." -> This should be hotspotted

**Comment by justineechen** [comment]
I don't think pom.xml should be hot spotted because we aren't really explaining anything in the code so there's no necessary reason to distract users by showing them the contents of the file.
