### ISSUE TITLE
SystemClient uses @RequestScoped and not @ApplicationScoped 

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guide-cdi-intro#82]
> I was wondering why is the SystemClient class in the example https://openliberty.io/guides/cdi-intro.html defined with scope @RequestScoped. It is injected in the InventoryManager which is @ApplicationScoped.
> 
> I would expect the same for it as well...
> 
> Thank you very much in advance, Fabio

https://stackoverflow.com/questions/55226545/openliberty-tutorial-injecting-dependencies-into-microservices

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/guide-cdi-intro/pull/83

**Comment by gkwan-ibm** [comment]
https://github.com/OpenLiberty/guide-cdi-intro/pull/87
