### ISSUE TITLE
InventoryManager not in sync with the guide

### ISSUE THREAD

**Issue by mesutcelik** [OpenLiberty/guide-cdi-intro#90]
When I check the `InventoryManager` class and its mention on the guide, I see that there are differences. Does that mean the code is out of sync or I am missing something?

```
@Inject
  private SystemClient systemClient;
```
This part is not available in the [code](https://github.com/OpenLiberty/guide-cdi-intro/blob/master/finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java#L28) but mentioned InventoryManager class in the [guide](https://openliberty.io/guides/cdi-intro.html#injecting-a-dependency)

**Comment by gkwan-ibm** [comment]
@mesutcelik the site will be refreshed soon. After refresh, the issue should be resolved, thanks

**Comment by gkwan-ibm** [comment]
@mesutcelik the site should be refreshed. Is the problem resolved?
